"""Emit a Unity Catalog Metric View YAML from a Cube spec.

Maps the Lakecube Cube model to the UC Metric View syntax (version 1.1).
Reference: https://docs.databricks.com/aws/en/metric-views/data-modeling/syntax

Mapping rules:
  - Cube.fact.table                   → source
  - Each non-measures Dimension       → one UC MV dimension entry
  - Alias tables                      → synonyms[] on the dimension
  - Cube.measures                     → UC MV measures
    * aggregation=sum|avg|min|max|count → AGG(source)
    * aggregation=formula               → emit formula verbatim; UC MV supports
                                          measure references
  - solve_order                       → comment hint (UC MV doesn't model it
                                          natively; Photon planner handles
                                          dependency order)

Hierarchies and member formulas from the measures-dimension are NOT emitted
here — UC Metric Views don't model them yet. Lakecube preserves them in a
sibling annotation file (emit_lakecube_annotations) for the Workbench +
Excel plugin to consume.
"""

from __future__ import annotations

import yaml

from lakecube.emitters.base import Artifact
from lakecube.spec import Cube, Dimension, Measure

_AGG_TO_SQL = {
    "sum": "SUM",
    "avg": "AVG",
    "min": "MIN",
    "max": "MAX",
    "count": "COUNT",
}


def _is_measures_dim(dim: Dimension) -> bool:
    """The "measures" dimension is a presentation concept; Cube.measures carries the real list."""
    return dim.type == "measures" or dim.name.lower() == "measures"


def _dim_entry(dim: Dimension, cube: Cube) -> dict:
    key_col = cube.fact.dimension_keys.get(dim.name, dim.name)
    entry: dict = {
        "name": dim.name,
        "expr": key_col,
    }
    if dim.aliases:
        entry["synonyms"] = list(dim.aliases.keys())[:10]
    if dim.type == "time":
        entry["comment"] = f"Time dimension, grain={dim.time_grain}"
    return entry


def _measure_entry(m: Measure) -> dict:
    entry: dict = {"name": m.name}
    if m.aggregation == "formula":
        if not m.formula:
            raise ValueError(f"measure {m.name}: aggregation=formula requires formula")
        entry["expr"] = m.formula
    else:
        agg = _AGG_TO_SQL.get(m.aggregation)
        if not agg:
            raise ValueError(f"measure {m.name}: unknown aggregation {m.aggregation!r}")
        source = m.source or m.name
        entry["expr"] = f"{agg}({source})"
    if m.solve_order:
        entry["comment"] = f"solve_order={m.solve_order}"
    if m.format:
        entry["format"] = {"display": m.format}
    return entry


def emit_metric_view(cube: Cube) -> Artifact:
    dimensions = [_dim_entry(d, cube) for d in cube.dimensions if not _is_measures_dim(d)]
    measures = [_measure_entry(m) for m in cube.measures]

    doc = {
        "version": "1.1",
        "comment": cube.description or f"Lakecube-compiled metric view for {cube.name}",
        "source": cube.fact.table,
    }
    if dimensions:
        doc["dimensions"] = dimensions
    if measures:
        doc["measures"] = measures

    yaml_body = yaml.safe_dump(doc, sort_keys=False, default_flow_style=False)
    view_name = f"lakecube_{cube.name}__mv"
    content = (
        f"-- Generated by Lakecube from cube.yaml — do not edit by hand.\n"
        f"CREATE OR REPLACE VIEW {view_name} AS $$\n{yaml_body}$$;\n"
    )
    return Artifact(
        path=f"metric_views/{cube.name}.sql",
        content=content,
        kind="metric_view",
    )
